# Generated by Django 4.2.5 on 2023-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
